image: Visual Studio 2019
version: 0.0.0.{build}
install:
- ps: |
    dotnet --version
    dotnet --list-sdks
    dotnet --list-runtimes
build_script:
- ps: .\ci\build-solution.ps1
test_script:
- ps: .\ci\run-test.ps1
artifacts:
- path: SumoLogic.Logging.Nuget\**.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: $(NUGET_API_KEY)
  on:
    appveyor_repo_tag: true
